name: flutter_chat
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  firebase_core: ^1.21.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_hooks: ^0.18.5+1
  freezed_annotation: ^2.1.0
  go_router: ^4.2.7
  graphql_codegen: ^0.11.0-beta.4
  graphql_flutter: ^5.1.1-beta.4
  hooks_riverpod: ^1.0.4
  intl: ^0.17.0
  json_annotation: ^4.6.0
  normalize: ^0.6.0+1
  quiver: ^3.1.0
  web_socket_channel: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
flutter:
  uses-material-design: true
  assets:
    - assets/env
scripts:
  generate: flutter pub run build_runner build --delete-conflicting-outputs
