// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'chat.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'chat.g.dart';

@freezed
class Chat with _$Chat {
  const factory Chat({
    required String key,
    required String data,
    required DateTime created,
    required String senderKey,
    required String recieverKey,
  }) = _Chat;

  factory Chat.fromJson(Map<String, Object?> json) => _$ChatFromJson(json);
}
