// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrvvigq_t7D-3ToV2MPXWqVK6zogRoWZc',
    appId: '1:209961189911:web:f0fd309209f22116251252',
    messagingSenderId: '209961189911',
    projectId: 'flutter-chat-6b603',
    authDomain: 'flutter-chat-6b603.firebaseapp.com',
    storageBucket: 'flutter-chat-6b603.appspot.com',
    measurementId: 'G-5K2N7TCCY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHNMUO8z2ZuYxdXYXM57rRB4n9h54ET2A',
    appId: '1:209961189911:android:1a7883034a62bef5251252',
    messagingSenderId: '209961189911',
    projectId: 'flutter-chat-6b603',
    storageBucket: 'flutter-chat-6b603.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv-kUSDd50lq0B0VAPaxZBupmoh3STzk4',
    appId: '1:209961189911:ios:d684e0c6005e60ec251252',
    messagingSenderId: '209961189911',
    projectId: 'flutter-chat-6b603',
    storageBucket: 'flutter-chat-6b603.appspot.com',
    iosClientId: '209961189911-obtrj919hks7c41g1ersuofsdsvgoksa.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv-kUSDd50lq0B0VAPaxZBupmoh3STzk4',
    appId: '1:209961189911:ios:d684e0c6005e60ec251252',
    messagingSenderId: '209961189911',
    projectId: 'flutter-chat-6b603',
    storageBucket: 'flutter-chat-6b603.appspot.com',
    iosClientId: '209961189911-obtrj919hks7c41g1ersuofsdsvgoksa.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChat',
  );
}
